#!/bin/sh

PIDFILE="/var/run/lf_notification.pid"
PID=$$

if [ -f "${PIDFILE}" ] && kill -CONT $( cat "${PIDFILE}" ); then
  echo "lf_notification is already running."
  exit 1
fi

echo "${PID}" > "${PIDFILE}"

while true; do
  cd /opt/liquid_feedback_frontend/
  echo "Event:send_notifications_loop()" | su www-data -c "../webmcp/framework.precompiled/bin/webmcp_shell piraten-lsa >> /var/log/lf_notification.log"
  date >> /var/log/lf_notification.log
  echo "Event:send_notifications_loop() terminated." >> /var/log/lf_notification.log
  sleep 60
done

